#!/bin/bash
if [ "$1" = "-title" -a "$3" = "-e" ]; then
	title="$2"
	shift 3
	# --title is deprecated so it'll stop working if your version doesn't support it
	# setting the title through escape sequences is ANNOYING so fuck that
	gnome-terminal --title "$title" -x "$@"
	exit
fi